server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**

        - id: product-route
          uri: lb://PRODUCT-SERVICE1
          predicates:
            - Path=/products/**

        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG